UWM_Clubs_and_Events/urls.py
from django.contrib import admin
from UWM_Clubs_and_Events.views.accountCalendar import accountCalendar
from UWM_Clubs_and_Events.views.CalendarView import CalendarView
from UWM_Clubs_and_Events.views.ClearAllFilters import ClearAllFilters
from UWM_Clubs_and_Events.views.ClearFilters import ClearFilters
from UWM_Clubs_and_Events.views.CreateAccount import CreateAccount
from UWM_Clubs_and_Events.views.CreateEvent import CreateEvent
from UWM_Clubs_and_Events.views.CreateOrganization import CreateOrganization
from UWM_Clubs_and_Events.views.EditAccount import EditAccount
from UWM_Clubs_and_Events.views.EditEvent import EditEvent
from UWM_Clubs_and_Events.views.EditOrganization import EditOrganization
from UWM_Clubs_and_Events.views.Homepage import Homepage
from UWM_Clubs_and_Events.views.login import login
from UWM_Clubs_and_Events.views.Logout import Logout
from UWM_Clubs_and_Events.views.OrgPage import OrgPage
from UWM_Clubs_and_Events.views.ViewAccount import ViewAccount
from UWM_Clubs_and_Events.views.ViewEvent import ViewEvent
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import CalendarView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login.as_view(), name='login'),
    path('login/', Logout.as_view(), name='logout'),
    path("login.html", login.as_view()),
    path('homepage/', Homepage.as_view(), name='homepage'),
    path('homepage/filter', ClearFilters.as_view(), name='clearfilters'),
    path('homepage/all', ClearAllFilters.as_view(), name='clearallfilters'),
    path('createAccount/', CreateAccount.as_view(), name='createaccount'),
    path('viewevent/<int:id>/', ViewEvent.as_view(), name='viewevent'),
    path('createAccount/', CreateAccount.as_view(), name='createaccount'),
    path('homepage/viewaccount/', ViewAccount.as_view(), name='viewaccount'),
    path('viewaccount/editaccount', EditAccount.as_view(), name='editaccount'),
    path('createOrganization/', CreateOrganization.as_view(), name='createorganization'),
    path('createEvent/', CreateEvent.as_view(), name='createevent'),
    path('editOrganization/', EditOrganization.as_view(), name='editorganization'),
    path('editEvent/<int:id>/', EditEvent.as_view(), name='editevent'),
    path('calendar/', CalendarView.as_view(), name='publicEvents'),
    path('all_events/', CalendarView.as_view(), name='all_events'),
    path('homepage/accountCalendar/', accountCalendar.as_view(), name='accountCalendar'),
    path('orgpage/<str:name>/', OrgPage.as_view(), name='orgpage'),

] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

UWM_Clubs_and_Events/models.py
from datetime import datetime

from django.db import models


# Model Fields: EmailField, CharField, IntegerField
# models.TextChoices
# to_field argument in Models.ForeignKey()

# name-str, email-str, password-str, role-?, interests/tags-?, orgs-?, majors-?, friends-?
# can edit:  Interest, Major, Graduation Date,
class User(models.Model):
    email = models.EmailField(max_length=30, unique=True)  # add email validator?
    password = models.CharField(max_length=30)
    role = models.PositiveSmallIntegerField(
        choices=((0, "Student"), (1, "Student Club Contact"), (2, "Organization"), (3, "Point of Contact")), default=0)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.email


class Student(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, to_field='email')
    enrollment_date = models.DateField(null=True)
    graduation_date = models.DateField(blank=True,null=True)

    def __str__(self):
        return self.user.email


# # Org/Club:  name-str, point_of_contact-str/email, membersCount-int, description-str, staff-User(staff to anchor),
# majors-?
class Organization(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, unique=True)
    point_of_contact = models.CharField(max_length=30)
    membersCount = models.IntegerField()
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


# Events:  name-str, organization-str, location-str, date-str/Date/Time, description-str, type-str, views-int
class Event(models.Model):
    name = models.CharField(max_length=30, unique=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, to_field='name')
    loc_addr = models.CharField(max_length=200)
    loc_state = models.CharField(max_length=200)
    loc_city = models.CharField(max_length=100)
    loc_zip = models.CharField(max_length=100)
    # this uses a YYYY-MM-DD for the date, and HH:MM:SS for the time
    time_happening = models.DateTimeField()  # look into these 2 fields some more
    description = models.TextField()
    time_published = models.DateTimeField(null=True)
    # if a user doesn't upload an image there will be a default image
    image = models.ImageField(upload_to='static/event_photos', default='static/event_photos/default.jpeg')

    # image here/file path for image?  where do we store/upload
    def __str__(self):
        return self.name + "/" + self.organization.name

    def delete(self, *args, **kwargs):
        self.image.delete(save=False)
        super(Event, self).delete(*args, **kwargs)


class MembersIn(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, to_field='email')
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, to_field='name')

    def __str__(self):
        return self.user.email + "/" + self.organization.name


class Major(models.Model):
    # consider using choices here for these?
    name = models.CharField(max_length=20, unique=True)
    department = models.CharField(max_length=20)

    def __str__(self):
        return self.name + "/" + self.department


class Interest(models.Model):
    tag = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.tag


class UserInterest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.ForeignKey(Interest, on_delete=models.CASCADE, to_field='tag')

    def __str__(self):
        return self.user.email + "/" + self.type.tag


class StudentInterest(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    type = models.ForeignKey(Interest, on_delete=models.CASCADE, to_field='tag')

    def __str__(self):
        return self.student.user.email + "/" + self.type.tag


class EventTag(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    interest = models.ForeignKey(Interest, on_delete=models.CASCADE, to_field='tag')

    def __str__(self):
        return self.event.name + "/" + self.interest.tag


class UserAttendEvent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email + "/" + self.event.name


class StudentMajor(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    major = models.ForeignKey(Major, on_delete=models.CASCADE, to_field='name')

    def __str__(self):
        return self.student.user.email + "/" + self.major.name


# class Friend(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, to_field='email')
#     friend_with = models.ForeignKey(User, on_delete=models.CASCADE, to_field='email')
#
#     def __str__(self):
#         return self.user.email + "/" + self.friend_with.email

# class PendingFriends(models.Model):
#     user_requester = models.ForeignKey(User, on_delete=models.CASCADE, to_field='email')
#     user_requested = models.ForeignKey(User, on_delete=models.CASCADE, to_field='email')
#
#     def __str__(self):
#         return "User " + self.user_requester.email + " sent user " + self.user_requested.email + " a friend request."

class Calendar(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    start = models.DateTimeField(null=True, blank=True)
    end = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "tblevents"

UWM_Clubs_and_Events/views/CalendarView.py
from datetime import timedelta

from django.http import JsonResponse
from django.views import View

from UWM_Clubs_and_Events.models import *


class CalendarView(View):
    def get(self, request):
        all_events = Event.objects.all()

        all_events = Event.objects.all()
        event_list = []

        for event in all_events:
            event_list.append({
                'title': event.name,
                'start': event.time_happening.strftime("%Y-%m-%dT%H:%M:%S"),
                'end': (event.time_happening + timedelta(hours=2)).strftime("%Y-%m-%dT%H:%M:%S"),

            })

        """ 
        if not request.user.is_authenticated:
            return JsonResponse([], safe=False)


        user_attend_events = UserAttendEvent.objects.filter(user=request.user)
        print("RSVP'd Events: ", user_attend_events) # debuging print statments
        events = [event.event for event in user_attend_events]
        print("Events: ", events)
        print("Current user: ", request.user.email)

        event_list = []
        for user_attend_event in user_attend_events:
            event = user_attend_event.event
            event_data= {
                'title': event.name,
                'start': event.time_happening.strftime("%Y-%m-%dT%H:%M:%S"),
                'end': (event.time_happening + timedelta(hours=2)).strftime("%Y-%m-%dT%H:%M:%S"),    
            }

            print(event_data)  # Debugging line
            event_list.append(event_data)

            """

        return JsonResponse(event_list, safe=False)

UWM_Clubs_and_Events/views/CreateAccount.py
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from UWM_Clubs_and_Events.models import *
from classes import user_util, event_util, organization_util
from django.core.paginator import Paginator
from django.http import JsonResponse
from datetime import timedelta


class CreateAccount(View):
    def get(self, request):
        search = request.GET.get('search-input', '')
        filtered_interests = Interest.objects.filter(tag__icontains=search)
        majors = Major.objects.all()
        return render(request, "createaccount.html", {"interests": filtered_interests, "majors": majors})

    def post(self, request):
        search = Interest.objects.all()
        allmajors = Major.objects.all()

        firstName = request.POST.get("firstname")
        lastName = request.POST.get("lastname")
        email = request.POST.get("email")
        password = request.POST.get("password")
        major = request.POST.getlist("majorlist")
        interests = request.POST.getlist("selected_interests")
        startdate = request.POST.get("startdate")
        graddate = request.POST.get("graddate")

        print(startdate)

        try:
            res = user_util.User_Util.create_user(name=firstName + " " + lastName, email=email, password=password,
                                                  role=0, startdate=startdate, graddate=graddate)
        except Exception as e:
            return render(request, "createaccount.html",
                          {"message": e, "interests": search, "fName": firstName, "lName": lastName, "email": email,
                           "startdate": startdate, "majors": allmajors})

        if isinstance(res, ValueError):
            return render(request, "createaccount.html",
                          {"message": res, "interests": search, "fName": firstName, "lName": lastName, "email": email,
                           "startdate": startdate, "majors": allmajors})

        # adds every tage fo interest to user

        for tags in interests:
            try:
                value = user_util.User_Util.set_user_interest(email=email, interest=tags)
            except Student.DoesNotExist:
                return render(request, "createaccount.html",
                              {"message": "student does not exists", "interests": search, "fName": firstName,
                               "lName": lastName, "email": email, "startdate": startdate, "majors": allmajors})
            # should not get here
            if isinstance(value, ValueError):
                return render(request, "createaccount.html",
                              {"message": value, "interests": search, "fName": firstName, "lName": lastName,
                               "email": email, "startdate": startdate, "majors": allmajors})

        for maj in major:
            add_major = user_util.User_Util.set_student_major(email=email, majorname=maj)

            if isinstance(add_major, ValueError):
                return render(request, "createaccount.html",
                              {"message": add_major, "interests": search, "fName": firstName, "lName": lastName,
                               "email": email, "startdate": startdate, "majors": allmajors})
        return render(request, "login.html", {"message": "user account successfully created"})

UWM_Clubs_and_Events/views/CreateEvent.py
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from UWM_Clubs_and_Events.models import *
from classes import user_util, event_util, organization_util
from django.core.paginator import Paginator
from django.http import JsonResponse
from datetime import timedelta

class CreateEvent(View):
    def get(self, request):
        tags = Interest.objects.all()
        current_user = user_util.User_Util.get_user(email=request.session['user'])
        if current_user.role == 2:
            orgs = Organization.objects.filter(user__exact=current_user)
        else:
            orgs = Organization.objects.filter(point_of_contact__exact=current_user.email)
        search = request.GET.get('search-input', '')
        filtered_interests = Interest.objects.filter(tag__icontains=search)
        return render(request, "createevent.html",
                      {"interests": filtered_interests, "orgs": orgs, "user": current_user, })

    def post(self, request):
        tags = Interest.objects.all()
        search = request.GET.get('search-input', '')

        name = request.POST.get('name')
        org_name = request.POST.get('org')

        time_happening = request.POST.get('time-happening')
        description = request.POST.get('description')
        time_published = datetime.now()
        photo = request.FILES.get('photo')
        current_user = user_util.User_Util.get_user(email=request.session['user'])
        orgs = Organization.objects.filter(point_of_contact__exact=current_user.email)
        search = request.GET.get('search-input', '')
        filtered_interests = Interest.objects.filter(tag__icontains=search)

        try:
            selected_org = Organization.objects.get(name=org_name)
        except Organization.DoesNotExist:
            return render(request, "createevent.html",
                          {"interests": filtered_interests, "orgs": orgs, "user": current_user,
                           "message": "Selected organization does not exist"})

        addr = request.POST.get('loc_addr')
        city = request.POST.get('loc_city')
        zip = request.POST.get('loc_zip')

        addr_check = event_util.Event_Util.verify_event_loc(addr, city, zip)
        if isinstance(addr_check, ValueError):
            return render(request, "createevent.html",
                          {'name': name, 'loc_addr': addr, 'loc_zip': zip, "interests": filtered_interests,
                           "description": description, "orgs": orgs, "user": current_user,
                           "time": time_happening, "message": addr_check})

        city_state = [part.strip() for part in city.split(',')]
        city_name = city_state[0]
        state_name = city_state[1]

        event = Event.objects.create(name=name, organization=selected_org, loc_addr=addr,
                                     loc_city=city_name,
                                     loc_state=state_name,
                                     loc_zip=zip,
                                     time_happening=time_happening, description=description,
                                     time_published=time_published, image=photo)
        event.save()
        print("event saved?")

        interests = request.POST.getlist("selected_interests")
        for tag in interests:
            eventTag = EventTag.objects.create(event=event, interest=Interest.objects.get(tag=tag))
            eventTag.save()
            # should not get here
            if isinstance(eventTag, ValueError):
                check = Interest.objects.all()
                return render(request, "createevent.html",
                              {"message": 'Search Tag could not be applied', "interests": check})

        return render(request, "createevent.html", {'message': 'Event created successfully',
                                                    "orgs": orgs,
                                                    "user": current_user,
                                                    "interests": filtered_interests})

UWM_Clubs_and_Events/views/accountCalendar.py
from django.shortcuts import render
from django.views import View

from UWM_Clubs_and_Events.models import *
from classes import user_util


class accountCalendar(View):
    def get(self, request):
        current_user = user_util.User_Util.get_user(email=request.session['user'])
        all_events = Event.objects.all()
        return render(request, "accountCalendar.html",
                      {"name": 'accountCalendar', 'events': all_events, 'user': current_user})

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Login</title>
    </head>
    <body>
    <!--Nav bar-->
    <nav class="navbar navbar-expand-lg bg-warning navbar-dark fixed-top py-3">
        <div class="container-fluid">
            <a href="#" class="navbar-brand text-dark"> UWM Clubs and Events </a>
            <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navmenu"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'createaccount' %}" class="nav-link text-dark">Create Account</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a href="{% url 'publicEvents'  %}" class="nav-link text-dark">Public Events</a>
                    </li> -->
                </ul>
            </div>
        </div>
    </nav>

    <!--Login form-->
    <div class="page_container">
        <div class="container mt-5 vh-90" style="padding-top: 70px; overflow: hidden;">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card bg-light">
                        <div class="card-body text-center">
                            <form style="max-width: 325px; margin : auto;" method="post" action="{% url 'login' %}">
                                {% csrf_token %}
                                <img src="{% static 'uwmLogo.jpg' %}" height="auto" width="100%" alt="Logo">
                                <h1 class="h3 mb-3 font-weight-normal text-center">Please Sign In</h1>
                                <label for="emailAddress" class="sr-only"></label>
                                <input type="email" name="email" id="id_email" class="form-control" placeholder="Email"
                                       required autofocus>
                                <label for="password" class="sr-only"></label>
                                <input type="password" name="password" id="id_password" placeholder="Password"
                                       class="form-control">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" value="Remember me"> Remember Me</label>
                                </div>

                                <!--sign in button-->
                                <div class="mt-3">
                                    <button class="btn btn-outline-lg btn-warning">Sign in</button>
                                </div>

                            </form>
                            <div style="color:green; padding:2%">
                                {% if success_message %}
                                    {{ success_message }}
                                {% endif %}
                            </div>
                            <div style="color:red; padding:2%">
                                {% if error_message %}
                                    {{ error_message }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    </body>
    </html>
{% endblock %}

templates/viewaccount.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>View Account</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-warning navbar-dark fixed-top py-3">
            <div class="container-fluid">
                <a href="{% url 'homepage' %}" class="navbar-brand text-dark" >UWM Clubs and Events </a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navmenu"
                >
                <span class = "navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navmenu">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{% url 'editaccount' %}" class="nav-link text-dark"> Edit Account </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item dropdown d-flex align-items-center">
                            <span class="me-2">👤</span>
                            <a href="#" class="nav-link text-dark dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ User.name }}</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                                <li><a class="dropdown-item" href="{% url 'accountCalendar' %}"> My Calendar</a></li>
                            <li><a class="dropdown-item" href="{% url 'viewaccount' %}">View Account</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Main Block -->
        <div class="page_container">
            <div class="container mt-5" style="padding-top: 60px; overflow: hidden;">
                <div class="row justify-content-center">
                    <div class="card bg-light">
                        <div class="card-body">
                            <div class="container">
                                <h1> Your Account Details </h1>
                                <form action="{% url 'viewaccount' %}" method="post">
                                    {% csrf_token %}
                                    {{ message }}
                                    <div class="card ">
                                        <div class="card-body">
                                            <h5 class="card-title">User Information</h5>
                                            <table class="table table-bordered">
                                                <tr>
                                                    <td>Name</td>
                                                    <td>{{ User.name }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Email</td>
                                                    <td>{{ User.email }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Role</td>
                                                    <td>{{ User.get_role_display }}</td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                    {% if User.role == 0 %}
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">Graduation Dates</h5>
                                                <table class="table table-bordered">
                                                    <tr>
                                                        <td>Start Graduation Date</td>
                                                        <td>{{ Stu.enrollment_date }}</td>
                                                    </tr>
                                                    <tr>
                                                        <td>End Graduation Date</td>
                                                        <td>{{ Stu.graduation_date }}</td>
                                                    </tr>
                                                </table>
                                            </div>
                                        </div>
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">Student Majors</h5>
                                                <ul class="list-group">
                                                    {% for umaj in usermajors %}
                                                        <li class="list-group-item">{{ umaj.major.name }}</li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">Student Interests</h5>
                                                <ul class="list-group">
                                                    {% for intm in userinterest %}
                                                        <li class="list-group-item">{{ intm.type.tag }}</li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>
                                    {% endif %}
                                    {% if User.role >= 2 %}
                                    <div class="card">
                                        <div class="card-body">
                                            <h5 class="card-title">User Organizations</h5>
                                            <ul class="list-group">
                                                {% for o in MemsInOrg %}
                                                    <li class="list-group-item">{{ o.organization.name }}</li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    </html>
{% endblock %}